### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vijayiyer05**
(wip) Suggested README updates to complete & center all the 4 ABO datasets

### CODE REVIEW

**Comment by vijayiyer05** [comment]
@ehennestad This is a near-complete README update per our conversation on Friday. It puts the datasets up front & center, with the first table focused on the quickstart examples, including your new one for Visual Behavior 2P. 

Your high-level (and any detailed) feedback welcomed. 

Known TODOs & decision points:

- Insert the view (from File Exchange) and run (via Open in MATLAB Online [link generator](https://www.mathworks.com/products/matlab-online/git.html)) links
- Maybe break up Visual Behavior Quickstart into a quickstart (shorter than current) & demo (slightly longer than current) to have Visual Behavior entries in both the first two tables? 
- Maybe update the schematic graphic to convey both Visual Coding & Visual Behavior conventions? 
- Maybe add run link for Visual Coding Neuropixels demo and/or tutorial if those are now runnable in MATLAB Online (basic)?

**Comment by vijayiyer05** [comment]
FYI @stevevanhooser, I believe this update (pending Eivind's review above) should make it easier for your intro anchored by the README. The initial section now includes all the ABO datasets & gives some description of each. Explaining the datasets should in my view be a key part of the short introduction.

**Review by ehennestad — COMMENTED** [review]
- I would drop the yellow smiley faces in the Experiment column of the first table
- The link in this sentence is not working: "and object representations of specific dataset items:"
- In the section "Using the Brain Observatory Toolbox", I would explain with text how the `listItem` functions are used to retrieve tables and the `getItems` functions are used to retrieve objects.
- Is it possible to divide the diagram in two and then also describe the workflow in a paragraph. Some of the concepts in the workflow diagram might need a bit more explaining, e.g on-demand values and linked files.

Some other ideas: 
- Add a table of contents at the top?
- Move the "Neural data analysis using the Allen Brain Observatory datasets" and place them next to and on the same level with the "Tutorial examples" section.

**Comment by ehennestad** [comment]
I am wondering if the text does not convey how the toolbox makes the data very easily accessible using local caching and on-demand object properties. This is of course obvious if you run the live scripts, but maybe a code snippet in the readme itself would bring this to the surface.

I.e, In three lines of code, you can retrieve neural data:
```
ophysSessionTable = bot.listSessions('VisualCoding', 'Ophys')
exampleSession = bot.getSessions( ophysSessionTable(1, :) )
dff = exampleSession.fluorescence_traces_dff
```

**Comment by ehennestad** [comment]
> Maybe update the schematic graphic to convey both Visual Coding & Visual Behavior conventions?

The only notable differences
1) The experiment is defined very differently in the Visual Coding and Visual Behavior datasets.
2) The Visual Behavior dataset includes "Behavior Only" sessions, but this is not yet supported in v0.9.4

**Comment by stevevanhooser** [comment]
Looking good here. I'm just confirming that I'll stand by to merge when it is no longer a draft.

**Comment by vijayiyer05** [comment]
Thanks @ehennestad/@stevevanhooser for the detailed/directional feedback on my first pass suggestions.

Have just completed another pass that adds a bit more text explanation & updates structure, along lines of Eivind's suggestions. Note: haven't yet broken up the image into two, so it simply repeats the image for now. 

@ehennestad : thoughts on how well this approach implements (or doesn't) the ideas you suggested? 

Re table-of-contents: it seems there is not a great way in GitHub. While there's a [built-in table-of-contents](https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/), it's not especially easy to find.

**Comment by ehennestad** [comment]
I like the current flow and division into the different sections!
For the table of contents, it could be a simple markdown list linking to the different sections, but as its a short and concise readme it might not be very necessary.
I also would not be too concerned about splitting the image if you don't have the source for it.

**Comment by vijayiyer05** [comment]
Adding 2 images that split up the prior workflow diagram...

BOTWorkflowSchematic
BOTItemsSchematic

**Comment by vijayiyer05** [comment]
Thank you @stevevanhooser & @ehennestad for the reviews. 

I've gone ahead and broken up the images into two. 

While there may be further tweaks in the days/weeks ahead, I suggest this is a good moment to **merge the PR** to affirm this is the intended direction/structure for the foreseeable future.

**Pull request merged**
